### ISSUE TITLE
AWS Secret key exposed

### ISSUE THREAD

**Issue by abhitnc** [saierukulla/erukulla#1]
Please check below URL

https://github.com/saierukulla/erukulla/blob/2e5b70fb8375ca3bc5aadfd8b640a185a4f21a2a/terraform.tfvars

**Comment by saierukulla** [comment]
i have removed the the terraform.tfvars file

**Comment by saierukulla** [comment]
> Please check below URL
> 
> https://github.com/saierukulla/erukulla/blob/2e5b70fb8375ca3bc5aadfd8b640a185a4f21a2a/terraform.tfvars

I have removed the terraform.tfvars file. But i am unable to upload any file. Can you let me know what is the issue.

**Comment by abhitnc** [comment]
Hi, I just found the AWS credentials open and reported.

**Comment by saierukulla** [comment]
Thanks for your update
But how did you got to know...that I have updated my keys file in git.

Regards
Sai
